//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Project/Settings/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""bf304a28-8b40-4935-8ed4-2145a71c5910"",
            ""actions"": [
                {
                    ""name"": ""HidePanel"",
                    ""type"": ""Button"",
                    ""id"": ""079673b4-71f3-4c65-9016-76d72ddd2ffa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""465e1d71-26e5-4855-9ab4-5497f251485d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseAll"",
                    ""type"": ""Button"",
                    ""id"": ""7b6e75dc-fd50-4a8f-bcd7-b6e3eea21c31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HideInventory"",
                    ""type"": ""Button"",
                    ""id"": ""8ed35440-1d44-4af8-a63b-8cdebb8883ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""961a0564-f8a6-4574-8d6d-d7e116518abf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitToMenu"",
                    ""type"": ""Button"",
                    ""id"": ""0eff651f-c60b-465c-9a0a-752d80b27891"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""49642e9f-2463-49c9-9f16-82be4b6af259"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""aebfe948-a13d-47eb-8472-3fbc8f421103"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84dd8f80-f7f7-4e26-986c-af56b05d91b0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e114f25b-1e94-4a6e-9e43-3f09125b5d50"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""UseAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afe90d89-0b2a-4e72-b986-2b0bae14ca50"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""HideInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f936db1-5fd4-4742-b0aa-eaa3099e4216"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acc26776-5054-4228-b2a8-54b082c64060"",
                    ""path"": ""<Keyboard>/end"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""ExitToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59dcd6ab-f903-44f8-bfd1-c6eec7d8ff7a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""HidePanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa20e1e9-4710-459c-ada1-8b6a402fc7e5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""NextDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5b4e5c6-2a27-4807-9537-fda361c670de"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""SkipDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Gameplay"",
            ""id"": ""0ea1d748-92df-486d-85a8-08211a48fe31"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""0eabcbf6-ea03-4dd7-a178-5dac88d6a257"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""49dcf7b1-c014-4f0c-b396-d87b309609b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability1"",
                    ""type"": ""Button"",
                    ""id"": ""a7f1e384-02a3-4aac-b571-94251fd7f5a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability2"",
                    ""type"": ""Button"",
                    ""id"": ""2655efdd-6f0e-4349-9f47-0b82b3f490ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability3"",
                    ""type"": ""Button"",
                    ""id"": ""b53e4770-3075-4496-a25b-37513352acdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityU"",
                    ""type"": ""Button"",
                    ""id"": ""3cc047c7-1e64-4c97-ad0b-d00b6110ca5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact1"",
                    ""type"": ""Button"",
                    ""id"": ""53b67cd5-f70c-42ad-85c0-8e292059cf0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact2"",
                    ""type"": ""Button"",
                    ""id"": ""96b2d38a-dd0e-4ac6-b076-06973e944311"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowPause"",
                    ""type"": ""Button"",
                    ""id"": ""42ea2042-a9fe-466d-98d6-0faf0bc3a225"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowInventory"",
                    ""type"": ""Button"",
                    ""id"": ""4393868c-99da-4bd7-995a-ede52c584b57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnterGame"",
                    ""type"": ""Button"",
                    ""id"": ""99a90c5a-a8ff-462e-8c6c-d5e1d8b6581b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveSide"",
                    ""type"": ""Button"",
                    ""id"": ""3904497c-9fa0-4798-8c38-7d28b4d3e2a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpSide"",
                    ""type"": ""Button"",
                    ""id"": ""63b000fe-ce50-46f5-bb01-b75b06939976"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchGravity"",
                    ""type"": ""Button"",
                    ""id"": ""6c157199-bc73-46e9-ac6d-4281b2e182e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard WASD"",
                    ""id"": ""77b8b4ed-6113-403d-b5c0-40c15de9d13a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""34eff479-f45e-45b1-ba18-85f7ea3802ab"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""78c9140f-bb78-4f30-950a-c25e643b1afa"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43e8443f-c4a7-4bc0-a470-3306daed7a7e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b1b894ea-36e0-45bb-a500-a281aed0470d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c9e33fb8-927f-466f-a84b-bbcfab1b33a4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caa78328-1f73-4ac2-b150-fe4b46b234a6"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""022d1187-48a0-45c8-a00f-96227b1ae9e3"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f6aaff9-c7ad-4b10-9cf2-9428b00b9a4a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc16cae2-f4d6-48b2-84a8-9fc84a051680"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Ability1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64c2d4de-0f56-4910-a3b3-3b87c12e715f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Ability2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaf1b83d-6e49-4bf3-9d92-d5a09ba73994"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Ability3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4290be86-20dc-4bd9-b87d-a9f4d1880145"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""AbilityU"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd5fefbc-eab8-4061-8969-c6688fe1a817"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Interact1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbbecca1-ecd2-4af3-b6d1-60b0ea52110b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Interact2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6afce49-8310-46b8-830f-4cb60bb542ac"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""ShowPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5e36de0-9150-411a-bdb5-666ef104d711"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""ShowInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d83e10de-1b1a-48b7-b74e-59c8745d1d51"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""EnterGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard AD"",
                    ""id"": ""c090bc62-8f81-46bc-9d26-f2aa4acb823e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSide"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f9e38cd7-f621-4da7-83fc-aefc0a2892f5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5bb53edb-8a68-4523-aace-e06a34cba2e7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""05e5edcc-c557-497d-b820-f0f31c6c946e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpSide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""978c2ac3-16a4-4df1-ac49-4c51a70d5abc"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchGravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Testing"",
            ""id"": ""70220496-189f-451f-b197-065346bd2eb6"",
            ""actions"": [
                {
                    ""name"": ""TakeDamage"",
                    ""type"": ""Button"",
                    ""id"": ""63c88859-6a6e-4c3e-9107-1f758875780b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""type"": ""Button"",
                    ""id"": ""374ab660-0dcd-4cd1-8aa0-c69a7c2fded9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6a4214d0-17e7-446e-8e0e-8acb3eeb1e9a"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""TakeDamage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23ca8311-ad8d-4234-8ee4-214377a84cbd"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Modifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardAndMouse"",
            ""bindingGroup"": ""KeyboardAndMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_HidePanel = m_UI.FindAction("HidePanel", throwIfNotFound: true);
        m_UI_UseItem = m_UI.FindAction("UseItem", throwIfNotFound: true);
        m_UI_UseAll = m_UI.FindAction("UseAll", throwIfNotFound: true);
        m_UI_HideInventory = m_UI.FindAction("HideInventory", throwIfNotFound: true);
        m_UI_SaveGame = m_UI.FindAction("SaveGame", throwIfNotFound: true);
        m_UI_ExitToMenu = m_UI.FindAction("ExitToMenu", throwIfNotFound: true);
        m_UI_NextDialogue = m_UI.FindAction("NextDialogue", throwIfNotFound: true);
        m_UI_SkipDialogue = m_UI.FindAction("SkipDialogue", throwIfNotFound: true);
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Sprint = m_Gameplay.FindAction("Sprint", throwIfNotFound: true);
        m_Gameplay_Ability1 = m_Gameplay.FindAction("Ability1", throwIfNotFound: true);
        m_Gameplay_Ability2 = m_Gameplay.FindAction("Ability2", throwIfNotFound: true);
        m_Gameplay_Ability3 = m_Gameplay.FindAction("Ability3", throwIfNotFound: true);
        m_Gameplay_AbilityU = m_Gameplay.FindAction("AbilityU", throwIfNotFound: true);
        m_Gameplay_Interact1 = m_Gameplay.FindAction("Interact1", throwIfNotFound: true);
        m_Gameplay_Interact2 = m_Gameplay.FindAction("Interact2", throwIfNotFound: true);
        m_Gameplay_ShowPause = m_Gameplay.FindAction("ShowPause", throwIfNotFound: true);
        m_Gameplay_ShowInventory = m_Gameplay.FindAction("ShowInventory", throwIfNotFound: true);
        m_Gameplay_EnterGame = m_Gameplay.FindAction("EnterGame", throwIfNotFound: true);
        m_Gameplay_MoveSide = m_Gameplay.FindAction("MoveSide", throwIfNotFound: true);
        m_Gameplay_JumpSide = m_Gameplay.FindAction("JumpSide", throwIfNotFound: true);
        m_Gameplay_SwitchGravity = m_Gameplay.FindAction("SwitchGravity", throwIfNotFound: true);
        // Testing
        m_Testing = asset.FindActionMap("Testing", throwIfNotFound: true);
        m_Testing_TakeDamage = m_Testing.FindAction("TakeDamage", throwIfNotFound: true);
        m_Testing_Modifier = m_Testing.FindAction("Modifier", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_HidePanel;
    private readonly InputAction m_UI_UseItem;
    private readonly InputAction m_UI_UseAll;
    private readonly InputAction m_UI_HideInventory;
    private readonly InputAction m_UI_SaveGame;
    private readonly InputAction m_UI_ExitToMenu;
    private readonly InputAction m_UI_NextDialogue;
    private readonly InputAction m_UI_SkipDialogue;
    public struct UIActions
    {
        private @InputActions m_Wrapper;
        public UIActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @HidePanel => m_Wrapper.m_UI_HidePanel;
        public InputAction @UseItem => m_Wrapper.m_UI_UseItem;
        public InputAction @UseAll => m_Wrapper.m_UI_UseAll;
        public InputAction @HideInventory => m_Wrapper.m_UI_HideInventory;
        public InputAction @SaveGame => m_Wrapper.m_UI_SaveGame;
        public InputAction @ExitToMenu => m_Wrapper.m_UI_ExitToMenu;
        public InputAction @NextDialogue => m_Wrapper.m_UI_NextDialogue;
        public InputAction @SkipDialogue => m_Wrapper.m_UI_SkipDialogue;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @HidePanel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnHidePanel;
                @HidePanel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnHidePanel;
                @HidePanel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnHidePanel;
                @UseItem.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUseItem;
                @UseItem.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUseItem;
                @UseItem.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUseItem;
                @UseAll.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUseAll;
                @UseAll.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUseAll;
                @UseAll.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUseAll;
                @HideInventory.started -= m_Wrapper.m_UIActionsCallbackInterface.OnHideInventory;
                @HideInventory.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnHideInventory;
                @HideInventory.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnHideInventory;
                @SaveGame.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSaveGame;
                @SaveGame.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSaveGame;
                @SaveGame.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSaveGame;
                @ExitToMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnExitToMenu;
                @ExitToMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnExitToMenu;
                @ExitToMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnExitToMenu;
                @NextDialogue.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNextDialogue;
                @NextDialogue.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNextDialogue;
                @NextDialogue.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNextDialogue;
                @SkipDialogue.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialogue;
                @SkipDialogue.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialogue;
                @SkipDialogue.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialogue;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HidePanel.started += instance.OnHidePanel;
                @HidePanel.performed += instance.OnHidePanel;
                @HidePanel.canceled += instance.OnHidePanel;
                @UseItem.started += instance.OnUseItem;
                @UseItem.performed += instance.OnUseItem;
                @UseItem.canceled += instance.OnUseItem;
                @UseAll.started += instance.OnUseAll;
                @UseAll.performed += instance.OnUseAll;
                @UseAll.canceled += instance.OnUseAll;
                @HideInventory.started += instance.OnHideInventory;
                @HideInventory.performed += instance.OnHideInventory;
                @HideInventory.canceled += instance.OnHideInventory;
                @SaveGame.started += instance.OnSaveGame;
                @SaveGame.performed += instance.OnSaveGame;
                @SaveGame.canceled += instance.OnSaveGame;
                @ExitToMenu.started += instance.OnExitToMenu;
                @ExitToMenu.performed += instance.OnExitToMenu;
                @ExitToMenu.canceled += instance.OnExitToMenu;
                @NextDialogue.started += instance.OnNextDialogue;
                @NextDialogue.performed += instance.OnNextDialogue;
                @NextDialogue.canceled += instance.OnNextDialogue;
                @SkipDialogue.started += instance.OnSkipDialogue;
                @SkipDialogue.performed += instance.OnSkipDialogue;
                @SkipDialogue.canceled += instance.OnSkipDialogue;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Sprint;
    private readonly InputAction m_Gameplay_Ability1;
    private readonly InputAction m_Gameplay_Ability2;
    private readonly InputAction m_Gameplay_Ability3;
    private readonly InputAction m_Gameplay_AbilityU;
    private readonly InputAction m_Gameplay_Interact1;
    private readonly InputAction m_Gameplay_Interact2;
    private readonly InputAction m_Gameplay_ShowPause;
    private readonly InputAction m_Gameplay_ShowInventory;
    private readonly InputAction m_Gameplay_EnterGame;
    private readonly InputAction m_Gameplay_MoveSide;
    private readonly InputAction m_Gameplay_JumpSide;
    private readonly InputAction m_Gameplay_SwitchGravity;
    public struct GameplayActions
    {
        private @InputActions m_Wrapper;
        public GameplayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Sprint => m_Wrapper.m_Gameplay_Sprint;
        public InputAction @Ability1 => m_Wrapper.m_Gameplay_Ability1;
        public InputAction @Ability2 => m_Wrapper.m_Gameplay_Ability2;
        public InputAction @Ability3 => m_Wrapper.m_Gameplay_Ability3;
        public InputAction @AbilityU => m_Wrapper.m_Gameplay_AbilityU;
        public InputAction @Interact1 => m_Wrapper.m_Gameplay_Interact1;
        public InputAction @Interact2 => m_Wrapper.m_Gameplay_Interact2;
        public InputAction @ShowPause => m_Wrapper.m_Gameplay_ShowPause;
        public InputAction @ShowInventory => m_Wrapper.m_Gameplay_ShowInventory;
        public InputAction @EnterGame => m_Wrapper.m_Gameplay_EnterGame;
        public InputAction @MoveSide => m_Wrapper.m_Gameplay_MoveSide;
        public InputAction @JumpSide => m_Wrapper.m_Gameplay_JumpSide;
        public InputAction @SwitchGravity => m_Wrapper.m_Gameplay_SwitchGravity;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Sprint.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSprint;
                @Ability1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility1;
                @Ability1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility1;
                @Ability1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility1;
                @Ability2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility2;
                @Ability2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility2;
                @Ability2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility2;
                @Ability3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility3;
                @Ability3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility3;
                @Ability3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbility3;
                @AbilityU.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbilityU;
                @AbilityU.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbilityU;
                @AbilityU.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAbilityU;
                @Interact1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract1;
                @Interact1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract1;
                @Interact1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract1;
                @Interact2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract2;
                @Interact2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract2;
                @Interact2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract2;
                @ShowPause.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShowPause;
                @ShowPause.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShowPause;
                @ShowPause.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShowPause;
                @ShowInventory.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShowInventory;
                @ShowInventory.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShowInventory;
                @ShowInventory.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShowInventory;
                @EnterGame.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEnterGame;
                @EnterGame.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEnterGame;
                @EnterGame.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEnterGame;
                @MoveSide.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveSide;
                @MoveSide.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveSide;
                @MoveSide.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveSide;
                @JumpSide.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJumpSide;
                @JumpSide.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJumpSide;
                @JumpSide.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJumpSide;
                @SwitchGravity.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchGravity;
                @SwitchGravity.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchGravity;
                @SwitchGravity.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchGravity;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Ability1.started += instance.OnAbility1;
                @Ability1.performed += instance.OnAbility1;
                @Ability1.canceled += instance.OnAbility1;
                @Ability2.started += instance.OnAbility2;
                @Ability2.performed += instance.OnAbility2;
                @Ability2.canceled += instance.OnAbility2;
                @Ability3.started += instance.OnAbility3;
                @Ability3.performed += instance.OnAbility3;
                @Ability3.canceled += instance.OnAbility3;
                @AbilityU.started += instance.OnAbilityU;
                @AbilityU.performed += instance.OnAbilityU;
                @AbilityU.canceled += instance.OnAbilityU;
                @Interact1.started += instance.OnInteract1;
                @Interact1.performed += instance.OnInteract1;
                @Interact1.canceled += instance.OnInteract1;
                @Interact2.started += instance.OnInteract2;
                @Interact2.performed += instance.OnInteract2;
                @Interact2.canceled += instance.OnInteract2;
                @ShowPause.started += instance.OnShowPause;
                @ShowPause.performed += instance.OnShowPause;
                @ShowPause.canceled += instance.OnShowPause;
                @ShowInventory.started += instance.OnShowInventory;
                @ShowInventory.performed += instance.OnShowInventory;
                @ShowInventory.canceled += instance.OnShowInventory;
                @EnterGame.started += instance.OnEnterGame;
                @EnterGame.performed += instance.OnEnterGame;
                @EnterGame.canceled += instance.OnEnterGame;
                @MoveSide.started += instance.OnMoveSide;
                @MoveSide.performed += instance.OnMoveSide;
                @MoveSide.canceled += instance.OnMoveSide;
                @JumpSide.started += instance.OnJumpSide;
                @JumpSide.performed += instance.OnJumpSide;
                @JumpSide.canceled += instance.OnJumpSide;
                @SwitchGravity.started += instance.OnSwitchGravity;
                @SwitchGravity.performed += instance.OnSwitchGravity;
                @SwitchGravity.canceled += instance.OnSwitchGravity;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Testing
    private readonly InputActionMap m_Testing;
    private ITestingActions m_TestingActionsCallbackInterface;
    private readonly InputAction m_Testing_TakeDamage;
    private readonly InputAction m_Testing_Modifier;
    public struct TestingActions
    {
        private @InputActions m_Wrapper;
        public TestingActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TakeDamage => m_Wrapper.m_Testing_TakeDamage;
        public InputAction @Modifier => m_Wrapper.m_Testing_Modifier;
        public InputActionMap Get() { return m_Wrapper.m_Testing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestingActions set) { return set.Get(); }
        public void SetCallbacks(ITestingActions instance)
        {
            if (m_Wrapper.m_TestingActionsCallbackInterface != null)
            {
                @TakeDamage.started -= m_Wrapper.m_TestingActionsCallbackInterface.OnTakeDamage;
                @TakeDamage.performed -= m_Wrapper.m_TestingActionsCallbackInterface.OnTakeDamage;
                @TakeDamage.canceled -= m_Wrapper.m_TestingActionsCallbackInterface.OnTakeDamage;
                @Modifier.started -= m_Wrapper.m_TestingActionsCallbackInterface.OnModifier;
                @Modifier.performed -= m_Wrapper.m_TestingActionsCallbackInterface.OnModifier;
                @Modifier.canceled -= m_Wrapper.m_TestingActionsCallbackInterface.OnModifier;
            }
            m_Wrapper.m_TestingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TakeDamage.started += instance.OnTakeDamage;
                @TakeDamage.performed += instance.OnTakeDamage;
                @TakeDamage.canceled += instance.OnTakeDamage;
                @Modifier.started += instance.OnModifier;
                @Modifier.performed += instance.OnModifier;
                @Modifier.canceled += instance.OnModifier;
            }
        }
    }
    public TestingActions @Testing => new TestingActions(this);
    private int m_KeyboardAndMouseSchemeIndex = -1;
    public InputControlScheme KeyboardAndMouseScheme
    {
        get
        {
            if (m_KeyboardAndMouseSchemeIndex == -1) m_KeyboardAndMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardAndMouse");
            return asset.controlSchemes[m_KeyboardAndMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IUIActions
    {
        void OnHidePanel(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnUseAll(InputAction.CallbackContext context);
        void OnHideInventory(InputAction.CallbackContext context);
        void OnSaveGame(InputAction.CallbackContext context);
        void OnExitToMenu(InputAction.CallbackContext context);
        void OnNextDialogue(InputAction.CallbackContext context);
        void OnSkipDialogue(InputAction.CallbackContext context);
    }
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnAbility1(InputAction.CallbackContext context);
        void OnAbility2(InputAction.CallbackContext context);
        void OnAbility3(InputAction.CallbackContext context);
        void OnAbilityU(InputAction.CallbackContext context);
        void OnInteract1(InputAction.CallbackContext context);
        void OnInteract2(InputAction.CallbackContext context);
        void OnShowPause(InputAction.CallbackContext context);
        void OnShowInventory(InputAction.CallbackContext context);
        void OnEnterGame(InputAction.CallbackContext context);
        void OnMoveSide(InputAction.CallbackContext context);
        void OnJumpSide(InputAction.CallbackContext context);
        void OnSwitchGravity(InputAction.CallbackContext context);
    }
    public interface ITestingActions
    {
        void OnTakeDamage(InputAction.CallbackContext context);
        void OnModifier(InputAction.CallbackContext context);
    }
}
